name: Build for Windows

on:
  push:
    branches: [master, develop, feature-*, hotfix-*, release-*]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sdkman/sdkman-action@master
      id: sdkman
      with:
        candidate: java
        version: 22.2.r17-grl
    - uses: actions/setup-java@1
      id: setup-java
      with:
        java-version: 17
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - name: Setup GRAALVM_HOME
      run: set GRAALVM_HOME=$JAVA_HOME
    - name: Build JAR with Maven
      run: mvn -B install
